### ISSUE TITLE
[BUG] spark358 build broken: GpuParquetUtilsShims not found after #14347 and #14359 merge

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids#14371]
## Description

The `spark358` shim build fails with a compilation error after the merge of #14347 and #14359 into `main`.

```
sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetUtils.scala:23:
  object GpuParquetUtilsShims is not a member of package com.nvidia.spark.rapids.shims.parquet

sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetUtils.scala:75:
  not found: value GpuParquetUtilsShims
```

## Root Cause

Two PRs merged close together, creating a gap:

1. **#14359** (`b6e721f1e`) — *Add support for Spark-3.5.8*: added shim files for `spark358` but did **not** include `GpuParquetUtilsShims.scala`.

2. **#14347** (`5f4dc5047`) — *Add support for PERFILE reader using cuDF deletion vector APIs*: introduced `GpuParquetUtilsShims` and added implementations only under `spark330/` and `spark340/`.

Since `spark358` does not have a `GpuParquetUtilsShims.scala` in its shim chain, `buildver=358` fails to compile.

## Existing shim files

```
sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/parquet/GpuParquetUtilsShims.scala  ✅
sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/parquet/GpuParquetUtilsShims.scala  ✅
sql-plugin/src/main/spark358/...  ❌ missing
```

## Expected Fix

Add a `GpuParquetUtilsShims.scala` shim file under the appropriate `spark35x` directory that `spark358` inherits from (likely a symlink or copy from the `spark340` version).

## Observed In

Pre-merge CI for unrelated PR #14369, `buildver=358` step.

**Comment by pxLi** [comment]
closed by https://github.com/NVIDIA/spark-rapids/pull/14374
