### ISSUE TITLE
[BUG] Delta Lake integration tests fail on Spark 4.1.3 (scala2.13) due to Delta 4.1.0 binary incompatibility

### ISSUE THREAD

**Issue by yinqingh** [NVIDIA/spark-rapids#15545]
**Describe the bug**
Build: rapids_integration-scala213-dev-github/122 (Spark 4.1.3, scala2.13, cuda12, Rocky8 + JDK17)

53 Delta Lake integration tests failed (543 passed, 187 skipped). All failures are in delta_lake_*_test.py modules. The loaded Delta jar is delta-spark_4.1_2.13-4.1.0.jar and is binary-incompatible with Spark 4.1.3: it references a Catalyst class missing from Spark 4.1.3 and a ParquetToSparkSchemaConverter constructor whose signature no longer matches. This causes the Python-side DeltaTable API to report the class is missing in the JVM. Appears tied to the newly added spark413 shim needing a compatible Delta version.

Error logs:
```
E  py4j.protocol.Py4JError: io.delta.tables.DeltaTable does not exist in the JVM
/tmp/spark-.../io.delta_delta-spark_4.1_2.13-4.1.0.jar/delta/tables.py:397: in forPath
    jdt = jvm.io.delta.tables.DeltaTable.forPath(jsparkSession, path, hadoopConf)

py4j.protocol.Py4JJavaError: An error occurred while calling o92.sql.
: java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/plans/logical/IgnoreCachedData
    at org.apache.spark.sql.delta.catalog.AbstractDeltaCatalog.$anonfun$alterTable$30(AbstractDeltaCatalog.scala:920)
    at org.apache.spark.sql.delta.catalog.AbstractDeltaCatalog.alterTable(AbstractDeltaCatalog.scala:699)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.catalyst.plans.logical.IgnoreCachedData

py4j.protocol.Py4JJavaError: An error occurred while calling o92.sql.
: java.lang.NoSuchMethodError: 'void org.apache.spark.sql.execution.datasources.parquet.ParquetToSparkSchemaConverter.<init>(boolean, boolean, boolean, boolean, boolean, boolean, boolean)'
    at org.apache.spark.sql.delta.Snapshot$.getParquetFileSchemaAndRowCount(Snapshot.scala:885)

==== 53 failed, 543 passed, 187 skipped, 16 warnings in 3633.73s (1:00:33) =====
```

**Environment details**
Spark 4.1.3 (shim spark413), Scala 2.13, CUDA12, Rocky8 + JDK17, Delta jar delta-spark_4.1_2.13-4.1.0.jar

**Comment by jihoonson** [comment]
It appears that this issue was caused by https://github.com/NVIDIA/cudf-spark/pull/15321.
