### PR TITLE
JDK17 build support in CI

### PR DESCRIPTION
**Pull request by pxLi**
related to #4103 

Add CI for JDK17 build of spark330
Also bump up javadoc version to resolve https://issues.apache.org/jira/browse/MJAVADOC-650

This change passed build and test(UT,IT) in internal pipeline 
and Actions CI https://github.com/NVIDIA/spark-rapids/actions/runs/4889935046/jobs/8728905893?pr=8234

We will enable regular jdk17-build pipeline after merge this one

I will upmerge after https://github.com/NVIDIA/spark-rapids/pull/8229

### CODE REVIEW

**Comment by pxLi** [comment]
build

File: .github/workflows/mvn-verify-check.yml [hunk 1]
```diff
@@ -140,4 +147,31 @@ jobs:
...
+
+      - name: Build JDK17
+        run: >
+          mvn -Dmaven.wagon.http.retryHandler.count=3 -B verify
+          -P 'individual,pre-merge'
+          -Dbuildver=${{ matrix.spark-version }}
+          -Dmaven.compiler.release=17
+          -Dmaven.compiler.source=17
+          -Dmaven.compiler.target=17
+          -Dscala.plugin.version=4.6.1
```
Comment (jlowe) [inline .github/workflows/mvn-verify-check.yml:173]: Is there a reason we wouldn't just change the default for this in pom.xml rather than needing to override it here?  Does 4.6.1 cause problems when not on JDK17?

File: .github/workflows/mvn-verify-check.yml [hunk 2]
```diff
@@ -140,4 +147,31 @@ jobs:
...
+          java-version: 17
+
+      - name: Build JDK17
+        run: >
+          mvn -Dmaven.wagon.http.retryHandler.count=3 -B verify
+          -P 'individual,pre-merge'
+          -Dbuildver=${{ matrix.spark-version }}
+          -Dmaven.compiler.release=17
+          -Dmaven.compiler.source=17
+          -Dmaven.compiler.target=17
```
Comment (jlowe) [inline .github/workflows/mvn-verify-check.yml:172]: Wondering if it would be better to encapsulate all the property changes needed for JDK17 into a jdk17 Maven profile in pom.xml to make it easier to use and maintain.  That profile was already added to dist/pom.xml, so it'd be nice to make it as easy as -Pjdk17 to build for JDK17.

File: .github/workflows/mvn-verify-check.yml (hunk 1 above)
Comment (pxLi) [reply .github/workflows/mvn-verify-check.yml:173]: I was following the doc, but yes let me try simply update the scala plugin version here

File: .github/workflows/mvn-verify-check.yml (hunk 2 above)
Comment (pxLi) [reply .github/workflows/mvn-verify-check.yml:172]: sure, I will make an update to the profiles of jdk 11 and 17

File: .github/workflows/mvn-verify-check.yml (hunk 1 above)
Comment (pxLi) [reply .github/workflows/mvn-verify-check.yml]: tried to bump up version, but seems the newer one may not be fully compatible w/ jdk version below 9
```
Error:  -release is only supported on Java 9 and higher
Warning:  Unexpected javac output: javac: invalid flag: --release
Usage: javac <options> <source files>
use -help for a list of possible options.
Error:  NoPosition: javac: invalid flag: --release
Warning:  javac exited with exit code 2
...
Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.6.1:compile (scala-compile-first) on project rapids-4-spark-sql_2.12: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.6.1:compile failed: javac returned non-zero exit code: CompileFailed 
```

I will add the version update to jdk11+ profiles

Comment (pxLi) [reply .github/workflows/mvn-verify-check.yml]:
```
[INFO] Compiler bridge installed
[INFO] compiling 372 Scala sources and 59 Java sources to /home/runner/work/spark-rapids/spark-rapids/sql-plugin/target/spark321cdh/classes ...
Error:  /home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala:112: value createUnintializedVector is not a member of com.google.flatbuffers.FlatBufferBuilder
Error:  /home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala:236: value createUnintializedVector is not a member of com.google.flatbuffers.FlatBufferBuilder
Error:  /home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala:253: type ByteBufferFactory is not a member of object com.google.flatbuffers.FlatBufferBuilder
Error:  /home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala:304: value createUnintializedVector is not a member of com.google.flatbuffers.FlatBufferBuilder
Error:  /home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala:320: overloaded method constructor FlatBufferBuilder with alternatives:
  (x$1: java.nio.ByteBuffer)com.google.flatbuffers.FlatBufferBuilder <and>
  ()com.google.flatbuffers.FlatBufferBuilder <and>
  (x$1: Int)com.google.flatbuffers.FlatBufferBuilder
 cannot be applied to (Int, com.nvidia.spark.rapids.DirectByteBufferFactory)
Error:  /home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala:329: overloaded method constructor FlatBufferBuilder with alternatives:
  (x$1: java.nio.ByteBuffer)com.google.flatbuffers.FlatBufferBuilder <and>
  ()com.google.flatbuffers.FlatBufferBuilder <and>
  (x$1: Int)com.google.flatbuffers.FlatBufferBuilder
 cannot be applied to (Int, com.nvidia.spark.rapids.DirectByteBufferFactory)
Error:  /home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala:343: overloaded method constructor FlatBufferBuilder with alternatives:
  (x$1: java.nio.ByteBuffer)com.google.flatbuffers.FlatBufferBuilder <and>
  ()com.google.flatbuffers.FlatBufferBuilder <and>
  (x$1: Int)com.google.flatbuffers.FlatBufferBuilder
 cannot be applied to (Int, com.nvidia.spark.rapids.DirectByteBufferFactory)
Error:  /home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/MetaUtils.scala:369: overloaded method constructor FlatBufferBuilder with alternatives:
  (x$1: java.nio.ByteBuffer)com.google.flatbuffers.FlatBufferBuilder <and>
  ()com.google.flatbuffers.FlatBufferBuilder <and>
  (x$1: Int)com.google.flatbuffers.FlatBufferBuilder
 cannot be applied to (Int, com.nvidia.spark.rapids.DirectByteBufferFactory)
Error: [ERROR] 8 errors found
```
we saw some compilation errors in cdh shims build after bump up scala.plugin.version to 4.6.1
let me revert scala.plugin.version to 4.3.0, and put 4.6.1 to jdk11+ profiles for now.

If needed, we can get back to fix compilation issues while using newer scala plugin later

File: .github/workflows/mvn-verify-check.yml (hunk 2 above)
Comment (pxLi) [reply .github/workflows/mvn-verify-check.yml]: Keep existing dist profiles there to avoid breaking other usages, and add new profiles <jdk11|jdk17-build> in parent pom for jdk11+ build properties

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

File: dist/pom.xml [hunk 3]
```diff
@@ -93,6 +93,14 @@
                 </included_buildvers>
             </properties>
         </profile>
+        <profile>
+            <id>jdk17</id>
```
Comment (jlowe) [inline dist/pom.xml:97]: I'm confused why there's a jdk17 vs. a jdk17-build profile, and it would be nice if there was just a single profile for JDK17.  If this is really desired, please add comments to these profiles explaining when one would be used vs. the other.  jdk17-build is documented in CONTRIBUTING, but jdk17 is not.

File: .github/workflows/mvn-verify-check.yml (hunk 1 above)
Comment (gerashegalov) [reply .github/workflows/mvn-verify-check.yml]: Scala plugin upgrade #5576 is also tracked as a task in #8181. And if the compilation issues affect just a few profiles, especially if just vendor profiles, we can pin the old version for them.

File: .github/workflows/mvn-verify-check.yml [hunk 4]
```diff
@@ -130,14 +137,31 @@ jobs:
...
         run: >
           mvn -Dmaven.wagon.http.retryHandler.count=3 -B verify
-          -P 'individual,pre-merge'
+          -P 'individual,pre-merge,jdk11-build'
+          -Dbuildver=${{ matrix.spark-version }}
+          -DskipTests
+          -Dskip
+          -Dmaven.javadoc.skip
+
+  verify-modules-with-jdk17:
```
Comment (gerashegalov) [inline .github/workflows/mvn-verify-check.yml:146]: the proliferation of this kind of copy and paste continues because we are not adding  jdk versions as a dimension to the build matrix

File: integration_tests/pom.xml [hunk 5]
```diff
@@ -417,7 +417,7 @@
             <plugin>
                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-javadoc-plugin</artifactId>
-                <version>3.0.0</version>
+                <version>3.3.2</version>
```
Comment (gerashegalov) [inline integration_tests/pom.xml:420]: Not sure if this for this PR but since you are touching this:

It looks like there are only one minor customization to the javadoc plugin between the parent pom and this pom.
We could delete the plugin definition here and add a parameter for `detectOfflineLinks` with the default value `true`. And this pom will merely override the parameter.

File: dist/pom.xml (hunk 3 above)
Comment (pxLi) [reply dist/pom.xml:97]: the profiles in dist/pom were only there for version-def usage in https://github.com/NVIDIA/spark-rapids/blob/branch-23.06/jenkins/version-def.sh#L55 before. If we need to combine them together, we will need to investigate if any other place is still depends on this one. 

I will add the TODO here

File: .github/workflows/mvn-verify-check.yml (hunk 1 above)
Comment (pxLi) [reply .github/workflows/mvn-verify-check.yml]: > especially if just vendor profiles, we can pin the old version for them.

I would like not to apply the change in this PR. We can follow up in https://github.com/NVIDIA/spark-rapids/issues/5576

File: integration_tests/pom.xml (hunk 5 above)
Comment (pxLi) [reply integration_tests/pom.xml:420]: thanks! I will try simplify the javadoc plugin def later

File: .github/workflows/mvn-verify-check.yml (hunk 4 above)
Comment (pxLi) [reply .github/workflows/mvn-verify-check.yml:146]: sure I will add a TODO here. If we are going to add more jdks, then we can refactor these to matrix later.
currently I would like to keep it as it is for now

**Comment by pxLi** [comment]
build

File: integration_tests/pom.xml [hunk 6]
```diff
@@ -417,17 +417,7 @@
...
-                        <goals>
-                            <goal>jar</goal>
-                        </goals>
-                    </execution>
-                </executions>
                 <configuration>
-                    <doclint>none</doclint>
                     <detectOfflineLinks>false</detectOfflineLinks>
                 </configuration>
             </plugin>
```
Comment (gerashegalov) [inline integration_tests/pom.xml]: This whole `<plugin>` definition is unnecessary. We merely need an override of the same-named user property `detectOfflineLinks` https://maven.apache.org/plugins/maven-javadoc-plugin/jar-mojo.html#detectOfflineLinks which should be added around [L30 in this pom](https://github.com/NVIDIA/spark-rapids/pull/8234/files/52ba01f13bd17c5a53c809160097f12c0a00d307..ce4a38836024a1a2b3a59067a14e2cc84e0fbeb1#diff-4b412ae5512cbf72928bdd8bfe6aa562a04f709fcbb7d97b04b6781e338ab987R30).

Comment (pxLi) [reply integration_tests/pom.xml]: I would like to keep it as a plugin dedicated configuration override instead of user property

Comment (pxLi) [reply integration_tests/pom.xml]: Adding `detectOfflineLinks` directly could confuse people, if they do not know if property, 
and we would have to add comment to explain where this property would be used. Also it may bring some conflict if other place using it w/ the same name.

To me, it does not bring any benefit to put it in property list (saving some code?). 
Explicitly adding to the plugin config seems more maintainable IMHO.

**Comment by pxLi** [comment]
@jlowe @gerashegalov can you help revisit this change? 
if no blocking issue, we would like to enable the regular run of jdk17 build and test first, thanks

If any style or preferences issue, please file tickets and I will follow up later, thanks!

**Review by jlowe — APPROVED** [review]

**Review by gerashegalov — APPROVED** [review]
