### ISSUE TITLE
[BUG] scala version hardcoded irrespective of Spark dependency

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#7775]
**Describe the bug**

Looking at #7767  I noticed that we may run into ABI incompatibilities due to hard-coding  the Scala version 2.12.15 instead of matching it to the one used to build the Spark dependency. 

Consider Scala 2.12.17  to which we might upgrade because it's used for the upcoming 340: https://github.com/apache/spark/blob/d18ee4d016caf18c9ad3691abbe9ebe442853300/pom.xml#L171 

Compiling the same shim with 2.12.15 vs 2.12.17 results in different bytecode files. Thus we will have either an ABI problem with 340 if we don't upgrade or with 331 if we do.

<details>
<summary>
See the diff 
<pre>
diff <(javap -verbose /tmp/321.1/com/nvidia/spark/rapids/AggregateModeInfo.class) <(javap -verbose /tmp/321.2/com/nvidia/spark/rapids/AggregateModeInfo.class)
</pre>
</summary>
<pre>
1,3c1,3
< Classfile /tmp/321.1/com/nvidia/spark/rapids/AggregateModeInfo.class
<   Last modified Feb 14, 2023; size 7266 bytes
<   MD5 checksum f95fb70c3ee0b42f1803cd1e62a8a650
---
> Classfile /tmp/321.2/com/nvidia/spark/rapids/AggregateModeInfo.class
>   Last modified Feb 14, 2023; size 7222 bytes
>   MD5 checksum 2bee9916b556edd786a88b4638642895
442,446c442,446
<                        1: 43
<                        2: 53
<                        3: 63
<                        4: 73
<                  default: 83
---
>                        1: 41
>                        2: 49
>                        3: 57
>                        4: 65
>                  default: 73
450,474c450,473
<         40: goto          95
<         43: aload_0
<         44: invokevirtual #67                 // Method hasPartialMode:()Z
<         47: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
<         50: goto          95
<         53: aload_0
<         54: invokevirtual #70                 // Method hasPartialMergeMode:()Z
<         57: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
<         60: goto          95
<         63: aload_0
<         64: invokevirtual #73                 // Method hasFinalMode:()Z
<         67: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
<         70: goto          95
<         73: aload_0
<         74: invokevirtual #76                 // Method hasCompleteMode:()Z
<         77: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
<         80: goto          95
<         83: new           #93                 // class java/lang/IndexOutOfBoundsException
<         86: dup
<         87: iload_1
<         88: invokestatic  #99                 // Method java/lang/Integer.toString:(I)Ljava/lang/String;
<         91: invokespecial #102                // Method java/lang/IndexOutOfBoundsException."<init>":(Ljava/lang/String;)V
<         94: athrow
<         95: areturn
<       StackMapTable: number_of_entries = 7
---
>         40: areturn
>         41: aload_0
>         42: invokevirtual #67                 // Method hasPartialMode:()Z
>         45: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
>         48: areturn
>         49: aload_0
>         50: invokevirtual #70                 // Method hasPartialMergeMode:()Z
>         53: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
>         56: areturn
>         57: aload_0
>         58: invokevirtual #73                 // Method hasFinalMode:()Z
>         61: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
>         64: areturn
>         65: aload_0
>         66: invokevirtual #76                 // Method hasCompleteMode:()Z
>         69: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
>         72: areturn
>         73: new           #93                 // class java/lang/IndexOutOfBoundsException
>         76: dup
>         77: iload_1
>         78: invokestatic  #99                 // Method java/lang/Integer.toString:(I)Ljava/lang/String;
>         81: invokespecial #102                // Method java/lang/IndexOutOfBoundsException."<init>":(Ljava/lang/String;)V
>         84: athrow
>       StackMapTable: number_of_entries = 6
478,484c477,481
<         frame_type = 6 /* same */
<         frame_type = 9 /* same */
<         frame_type = 9 /* same */
<         frame_type = 9 /* same */
<         frame_type = 9 /* same */
<         frame_type = 75 /* same_locals_1_stack_item */
<           stack = [ class java/lang/Object ]
---
>         frame_type = 4 /* same */
>         frame_type = 7 /* same */
>         frame_type = 7 /* same */
>         frame_type = 7 /* same */
>         frame_type = 7 /* same */
489,490c486,487
<             0      96     0  this   Lcom/nvidia/spark/rapids/AggregateModeInfo;
<             0      96     1   x$1   I
---
>             0      85     0  this   Lcom/nvidia/spark/rapids/AggregateModeInfo;
>             0      85     1   x$1   I
637c634
<          2: if_acmpeq     134
---
>          2: if_acmpeq     123
642c639
<         11: ifeq          19
---
>         11: ifeq          18
644,701c641,691
<         15: istore_2
<         16: goto          27
<         19: goto          22
<         22: iconst_0
<         23: istore_2
<         24: goto          27
<         27: iload_2
<         28: ifeq          138
<         31: aload_1
<         32: checkcast     #2                  // class com/nvidia/spark/rapids/AggregateModeInfo
<         35: astore        4
<         37: aload_0
<         38: invokevirtual #64                 // Method uniqueModes:()Lscala/collection/Seq;
<         41: aload         4
<         43: invokevirtual #64                 // Method uniqueModes:()Lscala/collection/Seq;
<         46: astore        5
<         48: dup
<         49: ifnonnull     61
<         52: pop
<         53: aload         5
<         55: ifnull        69
<         58: goto          130
<         61: aload         5
<         63: invokevirtual #140                // Method java/lang/Object.equals:(Ljava/lang/Object;)Z
<         66: ifeq          130
<         69: aload_0
<         70: invokevirtual #67                 // Method hasPartialMode:()Z
<         73: aload         4
<         75: invokevirtual #67                 // Method hasPartialMode:()Z
<         78: if_icmpne     130
<         81: aload_0
<         82: invokevirtual #70                 // Method hasPartialMergeMode:()Z
<         85: aload         4
<         87: invokevirtual #70                 // Method hasPartialMergeMode:()Z
<         90: if_icmpne     130
<         93: aload_0
<         94: invokevirtual #73                 // Method hasFinalMode:()Z
<         97: aload         4
<         99: invokevirtual #73                 // Method hasFinalMode:()Z
<        102: if_icmpne     130
<        105: aload_0
<        106: invokevirtual #76                 // Method hasCompleteMode:()Z
<        109: aload         4
<        111: invokevirtual #76                 // Method hasCompleteMode:()Z
<        114: if_icmpne     130
<        117: aload         4
<        119: aload_0
<        120: invokevirtual #142                // Method canEqual:(Ljava/lang/Object;)Z
<        123: ifeq          130
<        126: iconst_1
<        127: goto          131
<        130: iconst_0
<        131: ifeq          138
<        134: iconst_1
<        135: goto          139
<        138: iconst_0
<        139: ireturn
<       StackMapTable: number_of_entries = 10
---
>         15: goto          25
>         18: goto          21
>         21: iconst_0
>         22: goto          25
>         25: ifeq          127
>         28: aload_1
>         29: checkcast     #2                  // class com/nvidia/spark/rapids/AggregateModeInfo
>         32: astore        4
>         34: aload_0
>         35: invokevirtual #64                 // Method uniqueModes:()Lscala/collection/Seq;
>         38: aload         4
>         40: invokevirtual #64                 // Method uniqueModes:()Lscala/collection/Seq;
>         43: astore        5
>         45: dup
>         46: ifnonnull     58
>         49: pop
>         50: aload         5
>         52: ifnull        66
>         55: goto          127
>         58: aload         5
>         60: invokevirtual #140                // Method java/lang/Object.equals:(Ljava/lang/Object;)Z
>         63: ifeq          127
>         66: aload_0
>         67: invokevirtual #67                 // Method hasPartialMode:()Z
>         70: aload         4
>         72: invokevirtual #67                 // Method hasPartialMode:()Z
>         75: if_icmpne     127
>         78: aload_0
>         79: invokevirtual #70                 // Method hasPartialMergeMode:()Z
>         82: aload         4
>         84: invokevirtual #70                 // Method hasPartialMergeMode:()Z
>         87: if_icmpne     127
>         90: aload_0
>         91: invokevirtual #73                 // Method hasFinalMode:()Z
>         94: aload         4
>         96: invokevirtual #73                 // Method hasFinalMode:()Z
>         99: if_icmpne     127
>        102: aload_0
>        103: invokevirtual #76                 // Method hasCompleteMode:()Z
>        106: aload         4
>        108: invokevirtual #76                 // Method hasCompleteMode:()Z
>        111: if_icmpne     127
>        114: aload         4
>        116: aload_0
>        117: invokevirtual #142                // Method canEqual:(Ljava/lang/Object;)Z
>        120: ifeq          127
>        123: iconst_1
>        124: goto          128
>        127: iconst_0
>        128: ireturn
>       StackMapTable: number_of_entries = 8
703c693
<           offset_delta = 19
---
>           offset_delta = 18
705a696,697
>         frame_type = 67 /* same_locals_1_stack_item */
>           stack = [ int ]
707,712c699,700
<           offset_delta = 4
<           locals = [ class com/nvidia/spark/rapids/AggregateModeInfo, class java/lang/Object, int, class java/lang/Object ]
<           stack = []
<         frame_type = 255 /* full_frame */
<           offset_delta = 33
<           locals = [ class com/nvidia/spark/rapids/AggregateModeInfo, class java/lang/Object, int, class java/lang/Object, class com/nvidia/spark/rapids/AggregateModeInfo, class scala/collection/Seq ]
---
>           offset_delta = 32
>           locals = [ class com/nvidia/spark/rapids/AggregateModeInfo, class java/lang/Object, top, class java/lang/Object, class com/nvidia/spark/rapids/AggregateModeInfo, class scala/collection/Seq ]
715,717d702
<         frame_type = 60 /* same */
<         frame_type = 64 /* same_locals_1_stack_item */
<           stack = [ int ]
719c704
<           offset_delta = 2
---
>           offset_delta = 56
724c709
<           locals = [ int, class java/lang/Object ]
---
>           locals = [ top, class java/lang/Object ]
733,734c718,719
<             0     140     0  this   Lcom/nvidia/spark/rapids/AggregateModeInfo;
<             0     140     1   x$1   Ljava/lang/Object;
---
>             0     129     0  this   Lcom/nvidia/spark/rapids/AggregateModeInfo;
>             0     129     1   x$1   Ljava/lang/Object; 
</pre>
</details>

**Steps/Code to reproduce bug**
Compile 
```
mvn clean compile -pl sql-plugin -am -Dbuildver=321 -Dscala.version=2.12.15
```
and preserve `sql-plugin/target/spark321/classes`
to compare with the same path after 
```
mvn clean compile -pl sql-plugin -am -Dbuildver=321 -Dscala.version=2.12.17
```

**Expected behavior**
Make sure that bytecode is guaranteed backward-compatible or simply make sure that scala.version is different per 
shim profile.

**Environment details (please complete the following information)**
local dev

**Additional context**
#7767 
```[tasklist]

```

**Comment by revans2** [comment]
What happens with the common code? There is some code that cannot be shimmed. If we don't have ABI compatibility guarantees what version of scala do we use there? It sounds like we would have to have separate jars for different scala minor versions?

**Comment by revans2** [comment]
Also it looks like scala is guaranteeing some fairly decent level of compatibility.

https://docs.scala-lang.org/overviews/core/binary-compatibility-of-scala-releases.html

**Comment by gerashegalov** [comment]
> Also it looks like scala is guaranteeing some fairly decent level of compatibility.
> 
> https://docs.scala-lang.org/overviews/core/binary-compatibility-of-scala-releases.html

I am not sure it has always been the practice but hopefully indeed the diff is just some code that is backwards and forwards compatible 

> What happens with the common code? There is some code that cannot be shimmed. If we don't have ABI compatibility guarantees what version of scala do we use there? It sounds like we would have to have separate jars for different scala minor versions?

It's a very good question for this issue to answer. 
When we make the change of setting 2.12.17 only in 3.4 profile that I thought is necessary. If it generates a bytecode diff for unshimmable common files the build will fail. If our validation passes unshimmable code  than the worst case is that parallel worlds are larger but we don't need to worry about correctness.

**Comment by NVnavkumar** [comment]
I did some digging, and found some interesting results. So Spark 3.1.1  (lowest version we support)  is compiled with Scala 2.12.10. `spark-rapids` (as of the latest branch-23.08) does not compile with Scala 2.12.10 because the `nowarn` symbol is missing:

<details>
<summary>Compile errors with Scala 2.12.10</summary>

```
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuMultiFileReader.scala:122: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala:182: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetFileFormat.scala:269: value ENABLE_JOB_SUMMARY in class ParquetOutputFormat is deprecated: see corresponding Javadoc for more information.
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:671: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:718: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:992: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:1078: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:1084: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:1090: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:1096: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:1413: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:1517: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetUtils.scala:39: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetCachedBatchSerializer.scala:1275: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala:111: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala:195: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/ParquetSchemaUtils.scala:242: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/hiveUDFs.scala:50: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/rowBasedHiveUDFs.scala:110: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala:226: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuAvroScan.scala:1016: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala:218: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala:408: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuReadAvroFileFormat.scala:37: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastExchangeExec.scala:233: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/spark311/scala/org/apache/spark/storage/RapidsShuffleBlockFetcherIterator.scala:799: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/spark311/scala/org/apache/spark/storage/RapidsShuffleBlockFetcherIterator.scala:822: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/spark311/scala/org/apache/spark/storage/RapidsShuffleBlockFetcherIterator.scala:835: type nowarn is not a member of package annotation
[ERROR] [Error] /home/navink/src/spark-rapids/sql-plugin/src/main/spark311/scala/org/apache/spark/storage/RapidsShuffleBlockFetcherIterator.scala:846: type nowarn is not a member of package annotation
```
</details>

Ultimately, the lowest Scala version that branch-23.08 will compile with is Scala 2.12.13.

So I actually compiled the `sql-plugin` module with Scala 2.12.13, 2.12.15, and 2.12.17 using the 311 shim. Between 2.12.13 and 2.12.15, using a similar diff, there is no difference in bytecode with the `AggregateModeInfo.class`. 

```
$ diff <(javap -verbose /tmp/311.13/com/nvidia/spark/rapids/AggregateModeInfo.class) <(javap -verbose /tmp/311.15/com/nvidia/spark/rapids/AggregateModeInfo.class)
1c1
< Classfile /tmp/311.13/com/nvidia/spark/rapids/AggregateModeInfo.class
---
> Classfile /tmp/311.15/com/nvidia/spark/rapids/AggregateModeInfo.class
```

However it's different when comparing 2.12.13 and 2.12.17, *but* in what looks like the exact same way as between 2.12.15 and 2.12.17 and when using a different shim (here using 311 instead of 321).

<details>
<summary>Diff between 2.12.13 and 2.12.17 on the 311 shim</summary>

```
$ diff <(javap -verbose /tmp/311.13/com/nvidia/spark/rapids/AggregateModeInfo.class) <(javap -verbose /tmp/311.17/com/nvidia/spark/rapids/AggregateModeInfo.class)
1,3c1,3
< Classfile /tmp/311.13/com/nvidia/spark/rapids/AggregateModeInfo.class
<   Last modified Jun 5, 2023; size 7266 bytes
<   MD5 checksum a3a08a782d54ad148eb43beb86e00221
---
> Classfile /tmp/311.17/com/nvidia/spark/rapids/AggregateModeInfo.class
>   Last modified Jun 5, 2023; size 7222 bytes
>   MD5 checksum 8b65a2555b2c6613559d8db5c3c383ce
439,443c439,443
<                        1: 43
<                        2: 53
<                        3: 63
<                        4: 73
<                  default: 83
---
>                        1: 41
>                        2: 49
>                        3: 57
>                        4: 65
>                  default: 73
447,471c447,470
<         40: goto          95
<         43: aload_0
<         44: invokevirtual #67                 // Method hasPartialMode:()Z
<         47: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
<         50: goto          95
<         53: aload_0
<         54: invokevirtual #70                 // Method hasPartialMergeMode:()Z
<         57: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
<         60: goto          95
<         63: aload_0
<         64: invokevirtual #73                 // Method hasFinalMode:()Z
<         67: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
<         70: goto          95
<         73: aload_0
<         74: invokevirtual #76                 // Method hasCompleteMode:()Z
<         77: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
<         80: goto          95
<         83: new           #93                 // class java/lang/IndexOutOfBoundsException
<         86: dup
<         87: iload_1
<         88: invokestatic  #99                 // Method java/lang/Integer.toString:(I)Ljava/lang/String;
<         91: invokespecial #102                // Method java/lang/IndexOutOfBoundsException."<init>":(Ljava/lang/String;)V
<         94: athrow
<         95: areturn
<       StackMapTable: number_of_entries = 7
---
>         40: areturn
>         41: aload_0
>         42: invokevirtual #67                 // Method hasPartialMode:()Z
>         45: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
>         48: areturn
>         49: aload_0
>         50: invokevirtual #70                 // Method hasPartialMergeMode:()Z
>         53: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
>         56: areturn
>         57: aload_0
>         58: invokevirtual #73                 // Method hasFinalMode:()Z
>         61: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
>         64: areturn
>         65: aload_0
>         66: invokevirtual #76                 // Method hasCompleteMode:()Z
>         69: invokestatic  #91                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
>         72: areturn
>         73: new           #93                 // class java/lang/IndexOutOfBoundsException
>         76: dup
>         77: iload_1
>         78: invokestatic  #99                 // Method java/lang/Integer.toString:(I)Ljava/lang/String;
>         81: invokespecial #102                // Method java/lang/IndexOutOfBoundsException."<init>":(Ljava/lang/String;)V
>         84: athrow
>       StackMapTable: number_of_entries = 6
475,481c474,478
<         frame_type = 6 /* same */
<         frame_type = 9 /* same */
<         frame_type = 9 /* same */
<         frame_type = 9 /* same */
<         frame_type = 9 /* same */
<         frame_type = 75 /* same_locals_1_stack_item */
<           stack = [ class java/lang/Object ]
---
>         frame_type = 4 /* same */
>         frame_type = 7 /* same */
>         frame_type = 7 /* same */
>         frame_type = 7 /* same */
>         frame_type = 7 /* same */
486,487c483,484
<             0      96     0  this   Lcom/nvidia/spark/rapids/AggregateModeInfo;
<             0      96     1   x$1   I
---
>             0      85     0  this   Lcom/nvidia/spark/rapids/AggregateModeInfo;
>             0      85     1   x$1   I
634c631
<          2: if_acmpeq     134
---
>          2: if_acmpeq     123
639c636
<         11: ifeq          19
---
>         11: ifeq          18
641,698c638,688
<         15: istore_2
<         16: goto          27
<         19: goto          22
<         22: iconst_0
<         23: istore_2
<         24: goto          27
<         27: iload_2
<         28: ifeq          138
<         31: aload_1
<         32: checkcast     #2                  // class com/nvidia/spark/rapids/AggregateModeInfo
<         35: astore        4
<         37: aload_0
<         38: invokevirtual #64                 // Method uniqueModes:()Lscala/collection/Seq;
<         41: aload         4
<         43: invokevirtual #64                 // Method uniqueModes:()Lscala/collection/Seq;
<         46: astore        5
<         48: dup
<         49: ifnonnull     61
<         52: pop
<         53: aload         5
<         55: ifnull        69
<         58: goto          130
<         61: aload         5
<         63: invokevirtual #140                // Method java/lang/Object.equals:(Ljava/lang/Object;)Z
<         66: ifeq          130
<         69: aload_0
<         70: invokevirtual #67                 // Method hasPartialMode:()Z
<         73: aload         4
<         75: invokevirtual #67                 // Method hasPartialMode:()Z
<         78: if_icmpne     130
<         81: aload_0
<         82: invokevirtual #70                 // Method hasPartialMergeMode:()Z
<         85: aload         4
<         87: invokevirtual #70                 // Method hasPartialMergeMode:()Z
<         90: if_icmpne     130
<         93: aload_0
<         94: invokevirtual #73                 // Method hasFinalMode:()Z
<         97: aload         4
<         99: invokevirtual #73                 // Method hasFinalMode:()Z
<        102: if_icmpne     130
<        105: aload_0
<        106: invokevirtual #76                 // Method hasCompleteMode:()Z
<        109: aload         4
<        111: invokevirtual #76                 // Method hasCompleteMode:()Z
<        114: if_icmpne     130
<        117: aload         4
<        119: aload_0
<        120: invokevirtual #142                // Method canEqual:(Ljava/lang/Object;)Z
<        123: ifeq          130
<        126: iconst_1
<        127: goto          131
<        130: iconst_0
<        131: ifeq          138
<        134: iconst_1
<        135: goto          139
<        138: iconst_0
<        139: ireturn
<       StackMapTable: number_of_entries = 10
---
>         15: goto          25
>         18: goto          21
>         21: iconst_0
>         22: goto          25
>         25: ifeq          127
>         28: aload_1
>         29: checkcast     #2                  // class com/nvidia/spark/rapids/AggregateModeInfo
>         32: astore        4
>         34: aload_0
>         35: invokevirtual #64                 // Method uniqueModes:()Lscala/collection/Seq;
>         38: aload         4
>         40: invokevirtual #64                 // Method uniqueModes:()Lscala/collection/Seq;
>         43: astore        5
>         45: dup
>         46: ifnonnull     58
>         49: pop
>         50: aload         5
>         52: ifnull        66
>         55: goto          127
>         58: aload         5
>         60: invokevirtual #140                // Method java/lang/Object.equals:(Ljava/lang/Object;)Z
>         63: ifeq          127
>         66: aload_0
>         67: invokevirtual #67                 // Method hasPartialMode:()Z
>         70: aload         4
>         72: invokevirtual #67                 // Method hasPartialMode:()Z
>         75: if_icmpne     127
>         78: aload_0
>         79: invokevirtual #70                 // Method hasPartialMergeMode:()Z
>         82: aload         4
>         84: invokevirtual #70                 // Method hasPartialMergeMode:()Z
>         87: if_icmpne     127
>         90: aload_0
>         91: invokevirtual #73                 // Method hasFinalMode:()Z
>         94: aload         4
>         96: invokevirtual #73                 // Method hasFinalMode:()Z
>         99: if_icmpne     127
>        102: aload_0
>        103: invokevirtual #76                 // Method hasCompleteMode:()Z
>        106: aload         4
>        108: invokevirtual #76                 // Method hasCompleteMode:()Z
>        111: if_icmpne     127
>        114: aload         4
>        116: aload_0
>        117: invokevirtual #142                // Method canEqual:(Ljava/lang/Object;)Z
>        120: ifeq          127
>        123: iconst_1
>        124: goto          128
>        127: iconst_0
>        128: ireturn
>       StackMapTable: number_of_entries = 8
700c690
<           offset_delta = 19
---
>           offset_delta = 18
702a693,694
>         frame_type = 67 /* same_locals_1_stack_item */
>           stack = [ int ]
704,709c696,697
<           offset_delta = 4
<           locals = [ class com/nvidia/spark/rapids/AggregateModeInfo, class java/lang/Object, int, class java/lang/Object ]
<           stack = []
<         frame_type = 255 /* full_frame */
<           offset_delta = 33
<           locals = [ class com/nvidia/spark/rapids/AggregateModeInfo, class java/lang/Object, int, class java/lang/Object, class com/nvidia/spark/rapids/AggregateModeInfo, class scala/collection/Seq ]
---
>           offset_delta = 32
>           locals = [ class com/nvidia/spark/rapids/AggregateModeInfo, class java/lang/Object, top, class java/lang/Object, class com/nvidia/spark/rapids/AggregateModeInfo, class scala/collection/Seq ]
712,714d699
<         frame_type = 60 /* same */
<         frame_type = 64 /* same_locals_1_stack_item */
<           stack = [ int ]
716c701
<           offset_delta = 2
---
>           offset_delta = 56
721c706
<           locals = [ int, class java/lang/Object ]
---
>           locals = [ top, class java/lang/Object ]
730,731c715,716
<             0     140     0  this   Lcom/nvidia/spark/rapids/AggregateModeInfo;
<             0     140     1   x$1   Ljava/lang/Object;
---
>             0     129     0  this   Lcom/nvidia/spark/rapids/AggregateModeInfo;
>             0     129     1   x$1   Ljava/lang/Object;
```
</details>

**Comment by NVnavkumar** [comment]
Another question is did we ever look at MiMa (https://github.com/lightbend/mima)? I'm curious how possible this is to use given our parallel world build system.

**Comment by gerashegalov** [comment]
> Another question is did we ever look at MiMa (https://github.com/lightbend/mima)? I'm curious how possible this is to use given our parallel world build system.

I thought of using MiMa. We can use it in the `dist` somewhere before applying dedupe logic, or even somehow using it instead of dedupe logic. We can use [`mimaPreviousClassfiles`](https://github.com/lightbend/mima/blob/ba99c36e27ddadbda727b9d7c0d18c19b4bd184f/sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaKeys.scala#LL21C13-L21C35) to avoid having to publish artificial jars just to check compat.

**Comment by gerashegalov** [comment]
Re: https://github.com/NVIDIA/spark-rapids/issues/7775#issuecomment-1577578970

No further thoughts, I created this issue to figure out the nature of this diff and determine if there is an ABI impact

**Comment by NVnavkumar** [comment]
Closing since Scala makes binary compatibility guarantees for Scala 2.12 and we don't see any issues manifesting in integration tests (from Spark 3.1 to Spark 3.4).  Will file a followup issue for MiMa as a nice to have.
