### ISSUE TITLE
[BUG] not found: type PoissonDistribution in databricks build

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#3854]
**Describe the bug**
introduced in #3789 

```
[2021-10-19T01:39:36.689Z] [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuPoissonSampler.scala:22: object math3 is not a member of package org.apache.commons
[2021-10-19T01:39:36.689Z] [ERROR] import org.apache.commons.math3.distribution.PoissonDistribution
[2021-10-19T01:39:36.689Z] [ERROR]                           ^
[2021-10-19T01:39:36.689Z] [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuPoissonSampler.scala:31: not found: type PoissonDistribution
[2021-10-19T01:39:36.689Z] [ERROR]   private val rng = new PoissonDistribution(if (fraction > 0.0) fraction else 1.0)
[2021-10-19T01:39:36.689Z] [ERROR]                         ^
```
