### ISSUE TITLE
[BUG] branch-23.08 fails to build on Databricks 12.2

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#8493]
**Describe the bug**

```
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:30: object GpuCastShims is not a member of package com.nvidia.spark.rapids.shims
[ERROR] import com.nvidia.spark.rapids.shims.{AnsiUtil, GpuCastShims, GpuIntervalUtils, GpuTypeShims, SparkShimImpl, YearParseUtil}
[ERROR]        ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:466: not found: value GpuCastShims
[ERROR]         GpuCastShims.CastDecimalToString(input, ansiMode)
[ERROR]         ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala:30: Unused import
[ERROR] import com.nvidia.spark.rapids.shims.{AnsiUtil, GpuCastShims, GpuIntervalUtils, GpuTypeShims, SparkShimImpl, YearParseUtil}
[ERROR]                                                 ^
[ERROR] three errors found
```

**Steps/Code to reproduce bug**

**Expected behavior**

**Environment details (please complete the following information)**

**Additional context**

**Comment by revans2** [comment]
You probably just need to add https://github.com/NVIDIA/spark-rapids/blob/branch-23.06/sql-plugin/src/main/spark330db/scala/com/nvidia/spark/rapids/shims/GpuCastShims.scala to the shim for this version.
