### ISSUE TITLE
[BUG] Main branch build fails: GpuJsonToStructs.scala compile error - JSONUtils.FromJSONResult vs ColumnVector type mismatch

### ISSUE THREAD

**Issue by jihoonson** [NVIDIA/spark-rapids#15062]
**Describe the bug**
The main branch build fails across all runtimes (13.3, 14.3, 17.3 / Scala 2.12 and 2.13) during Scala compilation of the rapids-4-spark-sql module. The compiler reports that withResource cannot be applied to com.nvidia.spark.rapids.jni.JSONUtils.FromJSONResult and a type mismatch where FromJSONResult is found but ai.rapids.cudf.ColumnVector is required, in GpuJsonToStructs.scala at lines 60, 61 and 64. The build fails at scala-compile-first (InterfaceCompileFailed). 

Error logs:
```
[ERROR] .../sql/rapids/GpuJsonToStructs.scala:60: overloaded method value withResource with alternatives:
  [T <: AutoCloseable, V](r: T)(block: T => V)V
 cannot be applied to (com.nvidia.spark.rapids.jni.JSONUtils.FromJSONResult)
[ERROR] .../sql/rapids/GpuJsonToStructs.scala:61: type mismatch;
 found   : com.nvidia.spark.rapids.jni.JSONUtils.FromJSONResult
 required: ai.rapids.cudf.ColumnVector
[ERROR] .../sql/rapids/GpuJsonToStructs.scala:64: type mismatch;
 found   : com.nvidia.spark.rapids.jni.JSONUtils.FromJSONResult
 required: ai.rapids.cudf.ColumnVector
[ERROR] three errors found
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.7.1:compile (scala-compile-first) on project rapids-4-spark-sql_2.12: Compilation failed: InterfaceCompileFailed -> [Help 1]
```

**Comment by jihoonson** [comment]
The breaking change was introduced in https://github.com/NVIDIA/spark-rapids-jni/pull/4536. CC @wjxiz1992

**Comment by pxLi** [comment]
JNI revert has resolved this issue. closing this
