### ISSUE TITLE
[BUG] Databricks nightly build fails with "object roaringbitmap is not a member"

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#12260]
**Describe the bug**
```

[2025-03-04T14:10:16.376Z] [INFO] compiling 479 Scala sources and 29 Java sources to /home/ubuntu/spark-rapids/sql-plugin/target/spark330db/classes ...

[2025-03-04T14:10:16.376Z] [ERROR] [Error] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark320/scala/org/apache/spark/storage/RapidsPushBasedFetchHelper.scala:56: object roaringbitmap is not a member of package org

[2025-03-04T14:10:16.376Z] [ERROR] [Error] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark320/scala/org/apache/spark/storage/RapidsPushBasedFetchHelper.scala:96: not found: type RoaringBitmap

[2025-03-04T14:10:16.376Z] [ERROR] [Error] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark320/scala/org/apache/spark/storage/RapidsPushBasedFetchHelper.scala:135: not found: type RoaringBitmap

[2025-03-04T14:10:16.376Z] [ERROR] [Error] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark320/scala/org/apache/spark/storage/RapidsPushBasedFetchHelper.scala:155: not found: type RoaringBitmap

[2025-03-04T14:10:16.376Z] [ERROR] [Error] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark320/scala/org/apache/spark/storage/RapidsPushBasedFetchHelper.scala:158: type mismatch;
```

**Comment by gerashegalov** [comment]
It appears to be broken by #12208 cc @liurenjie1024
