### ISSUE TITLE
[BUG]spark job will hang in some situation

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#5064]
**Describe the bug**
This is an issue for spark 3.2.1, not related to the rapids plugin.

**Steps/Code to reproduce bug**
Env:
spark 3.2.1 local mode, just run ```./bin/pyspark  --driver-memory XXXXG --driver-cores XXXX```
run codes below:
```
path = "/XXXX/mortgage_eval_merged-small.csv"
src_data = sc.textFile(path).map(lambda x:x.split(","))
column_list = ['c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13','c14','c15','c16','c17','c18','c19','c20','c21','c22','c23','c24','c25','c26','c27','c28']
df = spark.createDataFrame(src_data,column_list)
print(df.show(1))
```
download dataset from here https://rapidsai-data.s3.us-east-2.amazonaws.com/spark/mortgage.zip
just 200000 rows could reproduce the issue ```head -n 200000 mortgage_eval_merged.csv > mortgage_eval_merged-small.csv``` but if the input dataset is small, such 50000 rows, it works well.

**Additional context**
this issue is specific to spark3.2.1, could not reproduce against spark3.2.0
![image](https://user-images.githubusercontent.com/84758614/160272712-0ddd8660-12c0-4d41-b325-bf4fa725473b.png)

**Comment by nvliyuan** [comment]
from The jstack log, it shows that the task is in the "waiting to be scheduled" state but cannot be scheduled.
![image](https://user-images.githubusercontent.com/84758614/160272371-2521dd2e-e8fb-44b0-bbcd-5b7587f52717.png)

**Comment by nvliyuan** [comment]
this is the good run on spark3.2.0
![image](https://user-images.githubusercontent.com/84758614/160272408-f2078795-3ce6-4f96-b894-e6521cc2e863.png)
![image](https://user-images.githubusercontent.com/84758614/160272416-b32a59f8-404e-4489-8433-4e9b1d5ec9c3.png)

**Comment by nvliyuan** [comment]
this is the waiting and blocking call tree, it seems that AsyncEventQueue is trying to get a lock, and the lock should timeout elapse but not, then it hangs.
![image](https://user-images.githubusercontent.com/84758614/160272616-46f5c5e4-07e4-443e-9add-08866f1c8455.png)
![image](https://user-images.githubusercontent.com/84758614/160272621-40b727a2-8e4b-478c-8f09-dc26dc918002.png)

**Comment by tgravescs** [comment]
This was just run in local mode? it sounds like there were not any executor threads running.

**Comment by tgravescs** [comment]
sorry missed it says local mode in description, I'm trying to reproduce

**Comment by tgravescs** [comment]
so it looks like the tasks was actually dying with the following error:
`  AttributeError: 'NoneType' object has no attribute 'items'`

Unfortunately I think local mode swallows it, sometimes running in standalone or yarn mode where you have real executors makes this type of error easier to find.

I'm investigating to see what is going on .

**Comment by tgravescs** [comment]
turns out I had a bad setup and it was pulling python 3.5 for the executor side. I ran in standalone mode on the same box and it works on Spark 3.2.1 with python 3.6, still looking at local mode.

**Comment by tgravescs** [comment]
Note this is open source spark issue not a plugin issue.  filed https://issues.apache.org/jira/browse/SPARK-38677 to address it.

**Comment by tgravescs** [comment]
this will be fixed in Spark 3.3.0 and 3.2.2, community PR is merged
