### ISSUE TITLE
[BUG] Build failure: rapids-4-spark-iceberg-stub IcebergProviderImpl.scala references missing Spark classes in Databricks shim build

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#14474]
**Describe the bug**
Build: rapids_databricks_nightly-dev-github/2165

The Databricks nightly build fails for all DB runtimes (12.2, 13.3, 14.3, 17.3) during Maven compilation of the new `rapids-4-spark-iceberg-stub` module introduced in commit 58524f4e. The file `iceberg/iceberg-stub/src/main/scala/.../icebergstub/IcebergProviderImpl.scala` imports Spark internal classes (`objects.StaticInvoke`, `Scan`, `Write`) that are not available in the classpath for the Databricks shim build profiles, causing 9 compile errors and a full build failure across all matrix legs.

Error logs:
```
[ERROR] [Error] IcebergProviderImpl.scala:22: object objects is not a member of package org.apache.spark.sql.catalyst.expressions
[ERROR] [Error] IcebergProviderImpl.scala:23: object Scan is not a member of package org.apache.spark.sql.connector.read
[ERROR] [Error] IcebergProviderImpl.scala:24: object Write is not a member of package org.apache.spark.sql.connector.write
[ERROR] [Error] IcebergProviderImpl.scala:31: not found: type Scan
[ERROR] [Error] IcebergProviderImpl.scala:32: not found: type StaticInvoke
[ERROR] [Error] IcebergProviderImpl.scala:33: not found: type StaticInvoke
[ERROR] [Error] IcebergProviderImpl.scala:34: not found: type Write
[ERROR] 9 errors found
[INFO] RAPIDS Accelerator for Apache Spark Iceberg Stub ... FAILURE [  2.739 s]
[INFO] BUILD FAILURE
```

**Environment details**
Databricks runtimes: 12.2 (Spark 3.3.2), 13.3 (Spark 3.4.1), 14.3 (Spark 3.5.0), 17.3 (Spark 4.0.0)
Commit: 58524f4e2e1f6c0a21de0cb64d46d4867eab00aa
Module: rapids-4-spark-iceberg-stub_2.12 / _2.13

**Comment by pxLi** [comment]
related to https://github.com/NVIDIA/spark-rapids/pull/14445, cc @liurenjie1024 to help thanks
