### ISSUE TITLE
[BUG] failed AnsiCastShim build in datasbricks 11.3 runtime

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#8164]
**Describe the bug**
failed build in databricks 11.3 runtime (work fine in 10.4 runtime), related to https://github.com/NVIDIA/spark-rapids/pull/8102

```
[2023-04-21T05:28:00.608Z] [INFO] Compiling 378 Scala sources and 59 Java sources to /home/ubuntu/spark-rapids/sql-plugin/target/spark330db/classes...

[2023-04-21T05:28:18.626Z] [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/AnsiCastShim.scala:38: object AnsiCast is not a member of package org.apache.spark.sql.catalyst.expressions

[2023-04-21T05:28:18.626Z] [ERROR] import org.apache.spark.sql.catalyst.expressions.{AnsiCast, Cast, Expression}

[2023-04-21T05:28:18.626Z] [ERROR]        ^

[2023-04-21T05:28:18.626Z] [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/AnsiCastShim.scala:43: not found: type AnsiCast

[2023-04-21T05:28:18.626Z] [ERROR]     case _: AnsiCast => true

[2023-04-21T05:28:18.626Z] [ERROR]             ^

[2023-04-21T05:28:18.626Z] [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/AnsiCastShim.scala:38: Unused import

[2023-04-21T05:28:18.626Z] [ERROR] import org.apache.spark.sql.catalyst.expressions.{AnsiCast, Cast, Expression}

[2023-04-21T05:28:18.626Z] [ERROR]                                                   ^

[2023-04-21T05:28:18.626Z] [ERROR] three errors found

```

**Steps/Code to reproduce bug**
build w/ `-Ddatabricks -Dbuildver=330db`

**Expected behavior**
pass the build

**Comment by pxLi** [comment]
cc @andygrove can you help check this one? thanks
