### PR TITLE
Fix dependencies in jenkins-test script to support DB11.3 [databricks]

### LINKED ISSUE #7112: Fix dependencies in jenkins-test script to support DB11.3
The test script jenkins/databricks/test.sh defines dependencies and path that does not work for DB11.3
In DB11.3, python version is 3.9 instead of 3.8, and the py4j file needs to be picked correctly. Currently it is hardcoded.

### PR DESCRIPTION
**Pull request by amahussein**
Signed-off-by: Ahmed Hussein (amahussein) <a@ahussein.me>

Fixes #7112 

This PR is part of the incremental steps to support DB-11.3.

**Changes**

1. Different DB runtimes might have different PYTHON. This PR pulls the correct version from the instance. This takes care of adding the correct site-packages to PYTHONPATH `export PYTHONPATH=/databricks/python3/lib/${sw_versions[PYTHON]}/site-packages:$PYTHONPATH`
2. Pull the correct file name `py4j-*-src.zip` from the instance. Otherwise, the PYTHONPATH would be broken for DB11.3 `PY4J_FILE=$(find $SPARK_HOME/python/lib -type f -iname "py4j*.zip") 
export PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/pyspark/:$PY4J_FILE`
3. The original  default ICEBERG_VERSION `0.13.2` is sot support on DB11.3. Added `0.14.1` as default to run on DB11.3.
4. Add instructions on usage, and how to extend the script to support new DB releases.

### CODE REVIEW

**Review by revans2 — DISMISSED** [review]

**Comment by amahussein** [comment]
build

File: jenkins/databricks/test.sh [hunk 1]
```diff
@@ -36,11 +61,37 @@ sudo "$(which pip)" install pytest sre_yield requests pandas pyarrow findspark p
...
+# Get Python version from environment after lowercase and remove minor.
+# Something like python3.8 for DB10.4 and python3.9 for DB11.3
+sw_versions[PYTHON]=$(python --version | sed 's/[A-Z]/\L&/g;s/ //g' | cut -d . -f 1,2)
+# set Iceberg related versions. See https://iceberg.apache.org/multi-engine-support/#apache-spark
+# Spark 3.3 | Initial Iceberg Version 0.14.0 | Latest Support 1.0.0
+# Spark 3.2 | Initial Iceberg Version 0.13.0 | Latest Support 1.0.0
+# Spark 3.1 | Initial Iceberg Version 0.12.0 | Latest Support 1.0.0
+case "$BASE_SPARK_VERSION" in
+    "3.3.0")
+        sw_versions[ICEBERG]=${ICEBERG_VERSION:-'0.14.1'}
```
Comment (tgravescs) [inline jenkins/databricks/test.sh:73]: we don't support 0.14.1... its fine to set it here I guess but at the same time wouldn't expect it to work so could confuse people. so seems like it should be skipped until we do

File: jenkins/databricks/test.sh [hunk 2]
```diff
@@ -36,11 +61,37 @@ sudo "$(which pip)" install pytest sre_yield requests pandas pyarrow findspark p
 export SPARK_HOME=/databricks/spark
 # change to not point at databricks confs so we don't conflict with their settings
 export SPARK_CONF_DIR=$PWD
-export PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/pyspark/:$SPARK_HOME/python/lib/py4j-0.10.9-src.zip
-if [[ $BASE_SPARK_VERSION == "3.2.1" ]]
+# Get Python version from environment after lowercase and remove minor.
+# Something like python3.8 for DB10.4 and python3.9 for DB11.3
+sw_versions[PYTHON]=$(python --version | sed 's/[A-Z]/\L&/g;s/ //g' | cut -d . -f 1,2)
+# set Iceberg related versions. See https://iceberg.apache.org/multi-engine-support/#apache-spark
+# Spark 3.3 | Initial Iceberg Version 0.14.0 | Latest Support 1.0.0
```
Comment (tgravescs) [inline jenkins/databricks/test.sh:68]: not sure what these comments mean, they don't match the versions below for 0.14.1, 0.13.2, etc..  so not sure why we need these?

Comment (amahussein) [reply jenkins/databricks/test.sh:68]: I can remove that table that shows the minimal version supported for each spark version.

File: jenkins/databricks/test.sh (hunk 1 above)
Comment (amahussein) [reply jenkins/databricks/test.sh:73]: Thanks @tgravescs ,
Then the default should be set to '0.14.0' to make it easy for manual testing.
According to https://github.com/NVIDIA/spark-rapids/pull/6098 Jenkins sets ICEBERG_VERSION to `0.14.0`

Comment (jlowe) [reply jenkins/databricks/test.sh:73]: #6104 reverted #6098.  There should be nothing referencing 0.14.0.

Comment (jlowe) [reply jenkins/databricks/test.sh:70]: > I updated run_iceberg_tests to skip iceberg for spark-3.4+ instead of spark-3.3+

Have you tested that change?  We compile against Iceberg 0.13, and that is not binary compatible with Iceberg 0.14, the latter which is required to run on Spark 3.3.x.

File: jenkins/databricks/test.sh [hunk 3]
```diff
@@ -36,11 +61,34 @@ sudo "$(which pip)" install pytest sre_yield requests pandas pyarrow findspark p
 export SPARK_HOME=/databricks/spark
 # change to not point at databricks confs so we don't conflict with their settings
 export SPARK_CONF_DIR=$PWD
-export PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/pyspark/:$SPARK_HOME/python/lib/py4j-0.10.9-src.zip
-if [[ $BASE_SPARK_VERSION == "3.2.1" ]]
+# Get Python version from environment after lowercase and remove minor.
```
Comment (gerashegalov) [inline jenkins/databricks/test.sh:64]: The third version component is called micro https://docs.python.org/3/library/sys.html#sys.version_info

File: jenkins/databricks/test.sh [hunk 4]
```diff
@@ -36,11 +61,34 @@ sudo "$(which pip)" install pytest sre_yield requests pandas pyarrow findspark p
...
+# Something like python3.8 for DB10.4 and python3.9 for DB11.3
+sw_versions[PYTHON]=$(python --version | sed 's/[A-Z]/\L&/g;s/ //g' | cut -d . -f 1,2)
```
Comment (gerashegalov) [inline jenkins/databricks/test.sh:66]: we can construct this value explicitly, also db seems to use different env variables to point to different Python uses  

```bash
${PYSPARK_PYTHON} -c 'import sys; print("python{}.{}".format(sys.version_info.major, sys.version_info.minor))'
```

File: jenkins/databricks/test.sh [hunk 5]
```diff
@@ -36,11 +61,34 @@ sudo "$(which pip)" install pytest sre_yield requests pandas pyarrow findspark p
...
+    *) echo "Unexpected Spark version: $BASE_SPARK_VERSION"; exit 1;;
+esac
+# Set the iceberg_spark to something like 3.3 for DB11.3, 3.2 for DB10.4
+sw_versions[ICEBERG_SPARK]=$(echo $BASE_SPARK_VERSION | cut -d. -f1,2)
+# Set ICEBERG scala version.
+sw_versions[ICEBERG_SCALA]=${ICEBERG_SCALA_VERSION:-'2.12'}
+# Get the correct py4j file.
+PY4J_FILE=$(find $SPARK_HOME/python/lib -type f -iname "py4j*.zip")
+export PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/pyspark/:$PY4J_FILE
+if [[ $BASE_SPARK_VERSION == "3.2.1" ]] || [[ $BASE_SPARK_VERSION == "3.3.0" ]]
```
Comment (gerashegalov) [inline jenkins/databricks/test.sh:87]: why is it conditional on the Spark version as a proxy for db runtime version? 
 
would this not work on 9.1? 
```
export PYTHONPATH=/databricks/python3/lib/${sw_versions[PYTHON]}/site-packages:$PYTHONPATH
```

File: jenkins/databricks/test.sh (hunk 1 above)
Comment (amahussein) [reply jenkins/databricks/test.sh:70]: Yeah, it is fine that the build does not support 0.14.
@gerashegalov and I decided to make the changes related to the profiler build of DB11.3 in [PR-7152: Add a shim for Databricks 11.3. Spark 3.3.0](https://github.com/NVIDIA/spark-rapids/pull/7152).
We need to be able to run the tests to continue fixing the new shims.

File: jenkins/databricks/test.sh (hunk 5 above)
Comment (amahussein) [reply jenkins/databricks/test.sh]: Interesting..This condition was added to support 10.4 so I didn't want to mess out with it.
According to DB documentation https://docs.databricks.com/archive/legacy/koalas.html

> Note
> Koalas is deprecated. If you try using Koalas on clusters that run [Databricks Runtime 10.0 (Unsupported)](https://docs.databricks.com/release-notes/runtime/10.0.html) and above, an informational message displays, recommending that you use [Pandas API on Spark](https://docs.databricks.com/pandas/pandas-on-spark.html) instead.

This means that we should not expect Koala on 10.4+. The original condition might be negated here.
I removed the condition in this PR.

@jlowe any thoughts?

Comment (jlowe) [reply jenkins/databricks/test.sh]: I don't know the full context behind this, other than we were seeing failures during the test collection phase on startup due to "bad" pandas ordering on the Python system path due to Koalas conflicting with the real Pandas modules such that one could no longer successfully import pandas.

You'll know whether or not it worked based on whether you can get past the test collection phase for udf_test.py and udf_cudf_test.py, as they both try to import pandas.

**Comment by amahussein** [comment]
build

**Comment by amahussein** [comment]
build

**Review by gerashegalov — DISMISSED** [review]
LGTM

confirmed on top of #7152 that without this PR we pytest fails to collect cudf-udf tests
```
______________ ERROR collecting src/main/python/udf_cudf_test.py _______________
../../src/main/python/udf_cudf_test.py:21: in <module>
    require_minimum_pandas_version()
/databricks/spark/python/pyspark/sql/pandas/utils.py:27: in require_minimum_pandas_version
    import pandas
/databricks/spark/python/pyspark/pandas/__init__.py:29: in <module>
    from pyspark.pandas.missing.general_functions import _MissingPandasLikeGeneralFunctions
/databricks/spark/python/pyspark/pandas/__init__.py:34: in <module>
    require_minimum_pandas_version()
/databricks/spark/python/pyspark/sql/pandas/utils.py:37: in require_minimum_pandas_version
    if LooseVersion(pandas.__version__) < LooseVersion(minimum_pandas_version):
E   AttributeError: partially initialized module 'pandas' has no attribute '__version__' (most likely due to a circular import)
```

whereas after the PR the tests are executed though fail which will be covered by #7184

File: jenkins/databricks/test.sh [hunk 6]
```diff
@@ -15,8 +15,33 @@
...
 #
 
+# This script sets the  environment to run tests of RAPIDS Accelerator for Apache Spark on DB.
+# All the environments can be overwritten by shell variables:
+#   LOCAL_JAR_PATH: Location of the RAPIDS jars
+#   SPARK_CONF: Spark configuration parameters
+#   BASE_SPARK_VERSION: Spark version [3.1.2, 3.2.1, 3.3.0]. Default is pulled from current instance.
+#   ICEBERG_VERSION: The iceberg version. To find the list of supported ICEBERG versions,
+#                    check https://iceberg.apache.org/multi-engine-support/#apache-spark
+#   ICEBERG_SCALA_VERSION: Scala version used by ICEBERG jars. Default is 2.12.
```
Comment (jlowe) [inline jenkins/databricks/test.sh:25]: I'm confused why this is called out explicitly.  How could we support pulling in a Scala version for Iceberg that doesn't match the Scala version used for all other jars?  If it's truly necessary, why are we not doing it for other jars with the Scala version in the artifact name?  Either this should be removed or a comment should be added explaining why this special case handling is necessary rather than using a consistent Scala version across all artifacts with a Scala version in the artifact name (e.g.: something like SCALA_VERSION used in jenkins/databricks/build.sh and jenkins/databricks/deploy.sh)

Comment (amahussein) [reply jenkins/databricks/test.sh]: - I fixed the SCALA version to be consistent. 
- I filed https://github.com/NVIDIA/spark-rapids/issues/7210 as followup to install the Iceberg jars provided by databricks in `jenkins/databricks.build.sh`
- I added a note in `docs/additional-functionality/iceberg-support.md` that the plugin does not support iceberg in databricks
- I clarified a comment in jenkins/spark-tests.sh that plugin is not supporting iceberg with spark3.3+

**Comment by amahussein** [comment]
build

File: jenkins/spark-tests.sh [hunk 7]
```diff
@@ -209,17 +211,19 @@ run_iceberg_tests() {
...
   # get the major/minor version of Spark
   ICEBERG_SPARK_VER=$(echo $SPARK_VER | cut -d. -f1,2)
+  IS_SPARK_33_OR_LATER=0
+  [[ "$(printf '%s\n' "3.3" "$ICEBERG_SPARK_VER" | sort -V | head -n1)" = "3.3" ]] && IS_SPARK_33_OR_LATER=1
 
-  # Iceberg does not support Spark 3.3+ yet
-  if [[ "$ICEBERG_SPARK_VER" < "3.3" ]]; then
-    PYSP_TEST_spark_jars_packages=org.apache.iceberg:iceberg-spark-runtime-${ICEBERG_SPARK_VER}_2.12:${ICEBERG_VERSION} \
+  # RAPIDS-iceberg does not support Spark 3.3+ yet
+  if [[ "$IS_SPARK_33_OR_LATER" -eq "1" ]]; then
```
Comment (jlowe) [inline jenkins/spark-tests.sh:218]: Nit: We should be consistent, using `=` above with double brackets, yet `-eq` here.
```suggestion
  if [[ "$IS_SPARK_33_OR_LATER" = "1" ]]; then
```

File: jenkins/spark-tests.sh [hunk 8]
```diff
@@ -209,17 +211,19 @@ run_iceberg_tests() {
...
+    echo "!!!! Skipping Iceberg tests. Iceberg does not support Spark $ICEBERG_SPARK_VER"
```
Comment (jlowe) [inline jenkins/spark-tests.sh:219]: Confusing message for some Spark versions where Iceberg does support it yet we're still going to skip.
```suggestion
    echo "!!!! Skipping Iceberg tests. GPU acceleration of Iceberg is not supported on Spark $ICEBERG_SPARK_VER"
```

**Comment by amahussein** [comment]
build

**Review by jlowe — APPROVED** [review]

**Review by gerashegalov — APPROVED** [review]
