### ISSUE TITLE
[BUG] Dataproc 2.2 image 2.2.84 breaks skewed BHJ optimizer: NoSuchMethodError on ShufflePartitionsUtil.createSkewPartitionSpecs

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#15373]
**Describe the bug**

`test_optimize_skewed_bhj_join` (private_optimizer_skewed_bhj_join_test.py) fails on the
`rapids-it-dataproc-2.2-ubuntu22` pipeline with a hard `NoSuchMethodError`:

```
java.lang.NoSuchMethodError: 'scala.Option org.apache.spark.sql.execution.adaptive.ShufflePartitionsUtil$.createSkewPartitionSpecs(int, int, long, double)'
    at com.nvidia.spark.rapids.internal.AQEUtils$.createSkewPartitionSpecs(AQEUtils.scala:67)
    at ...OptimizeSkewedBHJJoinRule.calculatePartitionSpec(OptimizeSkewedBHJJoinRule.scala:94)
    at ...OptimizeSkewedBHJJoinRule.apply(OptimizeSkewedBHJJoinRule.scala:259)
    at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.reOptimize(AdaptiveSparkPlanExec.scala:752)
    at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.executeCollect(AdaptiveSparkPlanExec.scala:421)
```

This is **not** a duplicate of #15136 (that is AQE-marker test instability on Databricks
runtimes). This is a deterministic binary incompatibility, and it affects real workloads on the
affected image, not just the test.

**Root cause**

The skew-join optimizer calls `ShufflePartitionsUtil.createSkewPartitionSpecs` with 3 arguments.
In every stock Apache Spark 3.3.0–3.5.6 that method is defined as 4-arg
`(int, int, long, double)` with a defaulted `smallPartitionFactor`, so the Scala compiler binds
the 3-arg source call to the **4-arg** method (plus `createSkewPartitionSpecs$default$4`) in the
shipped bytecode.

Dataproc's Spark build changed this signature **between image 2.2.81 and 2.2.84** — the 4-arg
overload is gone in 2.2.84, so the compiled call throws `NoSuchMethodError` at runtime.

**Steps to reproduce**

Run the skewed BHJ optimizer path (or `test_optimize_skewed_bhj_join`) on a Dataproc **2.2.84-ubuntu22**
cluster with the plugin enabled.

**Evidence it's the Dataproc image, not our code**

- The rule and the 3-arg call site are unchanged since 2023; the IT was added by #14902 (2026-06-08).
- Build **#234** ran on image **2.2.81-ubuntu22** → test **PASSED**.
- Build **#235** ran on image **2.2.84-ubuntu22** → **NoSuchMethodError** (same plugin code path).
- CI floated from 2.2.81 to 2.2.84 after the `2.2.81` image pin was removed (blossom-jenkins
  `remove 2.2.81 image pin`, merged 2026-07-21). The only test-side delta between #234 and #235
  is an unrelated Spark 4.2 skip.

**Expected behavior**

The skewed BHJ optimizer should work on Dataproc 2.2.84+ without a `NoSuchMethodError`.

**Environment details**
 - Environment location: Cloud (GCP Dataproc), image `2.2.84-ubuntu22`, Spark 3.5.x, GPU
 - Pipeline: `rapids-it-dataproc-2.2-ubuntu22` (#234 pass @2.2.81 → #235 fail @2.2.84)

**Possible fixes**
 - Make the plugin's `createSkewPartitionSpecs` call resilient to the arity change (e.g. reflectively
   bind to whichever overload the runtime Spark exposes), so it works on both stock Apache Spark and
   the modified Dataproc build.
 - Short-term CI unblock: re-pin the Dataproc image to `2.2.81` — but this hides the real user-facing
   break on 2.2.84 and should not be the final fix.

**Related**
 - #15136 — skewed BHJ AQE-marker test instability on Databricks runtimes (different root cause; not a duplicate).
 - #14902 — added the IT coverage that surfaces this path.

**Comment by yinqingh** [comment]
Also observed this error in dataproc 2.3 IT pipelines:
- rapids-it-dataproc-2.3-ml-ubuntu/1
- yinqing-rapids-it-dataproc (2.3-debian12)/158

**Comment by firestarman** [comment]
We have filed MR 397 to fix this issue.

**Comment by res-life** [comment]
MR 398 merged, close this issue.
