### PR TITLE
Fix not found: type PoissonDistribution in databricks build [databricks]

### LINKED ISSUE #3854: [BUG] not found: type PoissonDistribution in databricks build
**Describe the bug**
introduced in #3789 

```
[2021-10-19T01:39:36.689Z] [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuPoissonSampler.scala:22: object math3 is not a member of package org.apache.commons
[2021-10-19T01:39:36.689Z] [ERROR] import org.apache.commons.math3.distribution.PoissonDistribution
[2021-10-19T01:39:36.689Z] [ERROR]                           ^
[2021-10-19T01:39:36.689Z] [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuPoissonSampler.scala:31: not found: type PoissonDistribution
[2021-10-19T01:39:36.689Z] [ERROR]   private val rng = new PoissonDistribution(if (fraction > 0.0) fraction else 1.0)
[2021-10-19T01:39:36.689Z] [ERROR]                         ^
```

### PR DESCRIPTION
**Pull request by res-life**
This fixes #3854

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

**Comment by pxLi** [comment]
build
