### PR TITLE
Reverts NVIDIA/spark-rapids#10232 and fixes the plugin build on Databricks 11.3 [databricks]

### LINKED ISSUE #10432: Plug-in Build Failing for Databricks 11.3
**Describe the bug**
build is failing on Databricks 11.3. Possibly related to #10274 

```
INFO] Compiling 449 Scala sources and 58 Java sources to /home/ubuntu/spark-rapids/sql-plugin/target/spark330db/classes...
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala:29: object PythonWorker is not a member of package org.apache.spark.api.python
[ERROR] import org.apache.spark.api.python.{ChainedPythonFunctions, PythonRDD, PythonWorker}
[ERROR]        ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonOutput.scala:41: not found: type Writer
[ERROR]       writer: Writer,
[ERROR]               ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonOutput.scala:44: not found: type PythonWorker
[ERROR]       worker: PythonWorker,
[ERROR]               ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala:55: not found: type Writer
[ERROR]       context: TaskContext): Writer = {
[ERROR]                              ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala:52: not found: type PythonWorker
[ERROR]       worker: PythonWorker,
[ERROR]               ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala:56: not found: type Writer
[ERROR]     new Writer(env, worker, inputIterator, partitionIndex, context) {
[ERROR]         ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala:70: private method writeNextInputToStream in <$anon: <error>> is never used
[ERROR]       override def writeNextInputToStream(dataOut: DataOutputStream): Boolean = {
[ERROR]                    ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala:60: not found: type Writer
[ERROR]       context: TaskContext): Writer = {
[ERROR]                              ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala:57: not found: type PythonWorker
[ERROR]       worker: PythonWorker,  // Changed from "Socket" to this "PythonWorker" from db341
[ERROR]               ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala:61: not found: type Writer
[ERROR]     new Writer(env, worker, inputIterator, partitionIndex, context) {
[ERROR]         ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala:29: Unused import
[ERROR] import org.apache.spark.api.python.{ChainedPythonFunctions, PythonRDD, PythonWorker}
[ERROR]                                                                        ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuCoGroupedArrowPythonRunner.scala:73: private method writeNextInputToStream in <$anon: <error>> is never used
[ERROR]       override def writeNextInputToStream(dataOut: DataOutputStream): Boolean = {
[ERROR]                    ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala:68: not found: type Writer
[ERROR]       context: TaskContext): Writer = {
[ERROR]                              ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala:65: not found: type PythonWorker
[ERROR]       worker: PythonWorker, // From DB341, changed from Socket to PythonWorker
[ERROR]               ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala:69: not found: type Writer
[ERROR]     new Writer(env, worker, inputIterator, partitionIndex, context) {
[ERROR]         ^
[ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/spark330db/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuGroupUDFArrowPythonRunner.scala:81: private method writeNextInputToStream in <$anon: <error>> is never used
[ERROR]       override def writeNextInputToStream(dataOut: DataOutputStream): Boolean = {
```

### PR DESCRIPTION
**Pull request by razajafri**
Databricks has reverted the PythonRunner change which has caused the build to fail against Databricks 11.3

This PR reverts NVIDIA/spark-rapids#10232 and fixes the plugin build on Databricks 11.3

fixes #10432

### CODE REVIEW

**Comment by razajafri** [comment]
build

File: sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2023-2024, NVIDIA CORPORATION.
+ * Copyright (c) 2023, NVIDIA CORPORATION.
```
Comment (jlowe) [inline sql-plugin/src/main/spark311/scala/org/apache/spark/sql/rapids/execution/python/shims/GpuArrowPythonRunner.scala:2]: Copyrights should not have been reverted on this and a number of other files

**Comment by razajafri** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by razajafri** [comment]
premerge failed due to 
```
find: './.download/spark-3.1.1-bin-hadoop3.2/python/lib': Permission denied
```

**Comment by razajafri** [comment]
build
