### PR TITLE
[BUG] Add missing spark358 shim entry for GpuParquetUtilsShims

### LINKED ISSUE #14371: [BUG] spark358 build broken: GpuParquetUtilsShims not found after #14347 and #14359 merge
## Description

The `spark358` shim build fails with a compilation error after the merge of #14347 and #14359 into `main`.

```
sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetUtils.scala:23:
  object GpuParquetUtilsShims is not a member of package com.nvidia.spark.rapids.shims.parquet

sql-plugin/src/main/scala/com/nvidia/spark/rapids/parquet/GpuParquetUtils.scala:75:
  not found: value GpuParquetUtilsShims
```

## Root Cause

Two PRs merged close together, creating a gap:

1. **#14359** (`b6e721f1e`) — *Add support for Spark-3.5.8*: added shim files for `spark358` but did **not** include `GpuParquetUtilsShims.scala`.

2. **#14347** (`5f4dc5047`) — *Add support for PERFILE reader using cuDF deletion vector APIs*: introduced `GpuParquetUtilsShims` and added implementations only under `spark330/` and `spark340/`.

Since `spark358` does not have a `GpuParquetUtilsShims.scala` in its shim chain, `buildver=358` fails to compile.

## Existing shim files

```
sql-plugin/src/main/spark330/scala/com/nvidia/spark/rapids/shims/parquet/GpuParquetUtilsShims.scala  ✅
sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/parquet/GpuParquetUtilsShims.scala  ✅
sql-plugin/src/main/spark358/...  ❌ missing
```

## Expected Fix

Add a `GpuParquetUtilsShims.scala` shim file under the appropriate `spark35x` directory that `spark358` inherits from (likely a symlink or copy from the `spark340` version).

## Observed In

Pre-merge CI for unrelated PR #14369, `buildver=358` step.

### PR DESCRIPTION
**Pull request by wjxiz1992**
Closes #14371

## Summary

- Add the missing `{"spark": "358"}` entry to `GpuParquetUtilsShims.scala` in the `spark340` shim directory, fixing the `spark358` build failure.

## Root Cause

#14347 introduced `GpuParquetUtilsShims` with shim entries covering `spark340`–`spark357` and `spark400`+. #14359 then added the `spark358` shim version but did not update this file. All three sibling files in the same directory (`ParquetLegacyNanoAsLongShims`, `ParquetTimestampAnnotationShims`, `ParquetTimestampNTZShims`) already have the `358` entry — only `GpuParquetUtilsShims` was missed.

## Change

One line added to `sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/parquet/GpuParquetUtilsShims.scala`:

```
{"spark": "358"}
```

## Test plan

- [ ] Pre-merge CI `buildver=358` should now compile successfully

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Comment by wjxiz1992** [comment]
build

**Comment by wjxiz1992** [comment]
build

**Comment by wjxiz1992** [comment]
build

**Comment by pxLi** [comment]
build

**Review by res-life — APPROVED** [review]
LGTM

**Comment by pxLi** [comment]
dup of https://github.com/NVIDIA/spark-rapids/pull/14374
